development: &common
  enable_logging: yes
  autoload_paths:
    - app/models
  default_timezone: 'UTC'

test:
  <<: *common
  enable_logging: no

staging:
  <<: *common

production:
  <<: *common
  enable_logging: no
