# Defult database is used by default.
# Any models locating at app/models root directory will point to this database by default.
default:
  development: &common
    adapter: postgresql
    username:
    password:
    database: srum_development
    min_messages: WARNING
    reconnect: true
    pool: 5
    encoding: unicode
    host: localhost

  test:
    <<: *common
    database: srum_test

  production:
    <<: *common
    database: srum_production
